name: Frontend CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Frontend Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t suryathink/blogplatformassignment-frontend:latest ./client

      - name: Test Docker Image
        run: |
          echo "✅ Testing if Docker image runs properly..."
          docker run --rm -d --name test-frontend suryathink/blogplatformassignment-frontend:latest
          sleep 10
          docker logs test-frontend || true
          docker stop test-frontend || true

      - name: Push Docker Image to Docker Hub
        run: |
          docker push suryathink/blogplatformassignment-frontend:latest

      - name: Image Details
        run: |
          echo "🎉 Frontend Docker image pushed successfully!"
          echo "📦 Image: suryathink/blogplatformassignment-frontend:latest"
          echo "🔗 DockerHub: https://hub.docker.com/r/suryathink/blogplatformassignment-frontend"
